name: Java CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Build and Test
        run: mvn clean test

      - name: SonarCloud Analysis
        run: >
          mvn org.sonarsource.scanner.maven:sonar-maven-plugin:4.0.0.4121:sonar
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.projectKey=mrfarvees-official_product-service
          -Dsonar.organization=mrfarvees-official
          -Dsonar.branch.name=main
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}